# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.6/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/ulab/Desktop/project_6/project_6.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/ulab/Desktop/project_6/project_6.srcs/sources_1/ip/blk_mem_gen_v7_3_5/coregen.cgc"

set ipFile "c:/Users/ulab/Desktop/project_6/project_6.srcs/sources_1/ip/blk_mem_gen_v7_3_5/PSRAM_Buffer.xco"

set ipName "PSRAM_Buffer"

set hdlType "VHDL"

set cgPartSpec "xc7a100t-1csg324"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "c:/Users/ulab/Desktop/project_6/project_6.srcs/sources_1/ip/blk_mem_gen_v7_3_5/pa_cg_bom.xml"

# generate the IP
set result [source "c:/Xilinx/14.6/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

