# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.6/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/ulab/Desktop/project_6/project_6.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/ulab/Desktop/project_6/project_6.srcs/sources_1/ip/blk_mem_gen_v7_3_2/coregen.cgc"

set ipFile "c:/Users/ulab/Desktop/project_6/project_6.srcs/sources_1/ip/blk_mem_gen_v7_3_2/LCDinitROM.xco"

set ipName "LCDinitROM"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "c:/Users/ulab/Desktop/project_6/project_6.srcs/sources_1/ip/blk_mem_gen_v7_3_2/pa_cg_bom.xml"

set cgPartSpec "xc7a100t-1csg324"

set hdlType "VHDL"

# generate the IP
set result [source "c:/Xilinx/14.6/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

